"""widen node id columns to numeric for uint64 range

Revision ID: 19e1df64ff82
Revises: 470593e269ba
Create Date: 2026-08-23 07:11:49.414721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e1df64ff82'
down_revision: Union[str, Sequence[str], None] = '470593e269ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('governance_records', 'source_node_id',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=True)
    op.alter_column('governance_records', 'dest_node_id',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=True)
    op.alter_column('governance_records', 'dest_scope',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(precision=20, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('governance_records', 'dest_scope',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('governance_records', 'dest_node_id',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('governance_records', 'source_node_id',
               existing_type=sa.Numeric(precision=20, scale=0),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
