"""add mandatory reason to approval requests

Revision ID: 22a98b8d9b4d
Revises: c121db2d201d
Create Date: 2026-08-23 07:23:16.741347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a98b8d9b4d'
down_revision: Union[str, Sequence[str], None] = 'c121db2d201d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('reason', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'reason')
    # ### end Alembic commands ###
