"""create governance tables

Revision ID: 387793def642
Revises: 
Create Date: 2026-08-23 07:03:02.352559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387793def642'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_log_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_instance_id', sa.UUID(), nullable=False),
    sa.Column('log_seq', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('source_node_id', sa.BigInteger(), nullable=True),
    sa.Column('dest_node_id', sa.BigInteger(), nullable=True),
    sa.Column('dest_scope', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_instance_id'], ['governance_log_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_instance_id', 'log_seq', name='uq_governance_records_log_instance_seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_records')
    op.drop_table('governance_log_instances')
    # ### end Alembic commands ###
