"""add action check constraint

Revision ID: 470593e269ba
Revises: 387793def642
Create Date: 2026-08-23 07:08:37.418528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470593e269ba'
down_revision: Union[str, Sequence[str], None] = '387793def642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_governance_records_action', 'governance_records', "action IN ('promotion', 'promotion_rejected', 'promotion_unscoped_anomaly')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_governance_records_action', 'governance_records', type_='check')
    # ### end Alembic commands ###
