"""add erasure workflow (task 5c)

Revision ID: 57beb688a09c
Revises: 22a98b8d9b4d
Create Date: 2026-08-23 07:44:29.487562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57beb688a09c'
down_revision: Union[str, Sequence[str], None] = '22a98b8d9b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erasure_cases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('approval_request_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_request_id')
    )
    # ### end Alembic commands ###

    # NOT auto-detected (CHECK constraint diffs never are -- same gap the
    # previous 'add action check constraint' migration hit): widen
    # ck_governance_records_action to admit erasure.py's new "erasure"
    # action value (governance.py's GOVERNANCE_RECORD_ACTIONS).
    op.drop_constraint('ck_governance_records_action', 'governance_records', type_='check')
    op.create_check_constraint(
        'ck_governance_records_action',
        'governance_records',
        "action IN ('promotion', 'promotion_rejected', 'promotion_unscoped_anomaly', 'erasure')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_governance_records_action', 'governance_records', type_='check')
    op.create_check_constraint(
        'ck_governance_records_action',
        'governance_records',
        "action IN ('promotion', 'promotion_rejected', 'promotion_unscoped_anomaly')",
    )
    op.drop_table('erasure_cases')
    # ### end Alembic commands ###
